FactoryBot.define do
  factory :asset do
    organization
    name          { Faker::Commerce.product_name }
    serial_number { Faker::Alphanumeric.alphanumeric(number: 12).upcase }
    status        { "operational" }
    custom_fields { {} }
    # asset_tag is auto-generated by the model (FF-000001 format) if not supplied

    trait :with_location do
      association :location
    end

    trait :down do
      status { "down" }
    end

    trait :degraded do
      status { "degraded" }
    end

    trait :decommissioned do
      status { "decommissioned" }
    end

    trait :discarded do
      discarded_at { 1.hour.ago }
    end
  end
end
