class IoTRuleEvaluatorJob < ApplicationJob
  queue_as :iot

  def perform(asset_id, readings)
    rules = IotRule.active.for_asset(asset_id).includes(:asset, :organization)

    rules.each do |rule|
      value = readings[rule.metric_name]&.to_f
      next if value.nil?
      next unless rule.triggered_by?(value)
      next if recently_triggered?(rule)

      create_work_order(rule, value) if rule.auto_create_wo?
      mark_triggered(rule)
    end
  end

  private

  def recently_triggered?(rule)
    cooldown_key = "iot_rule_cooldown:#{rule.id}"
    Redis.new(url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0")).get(cooldown_key).present?
  end

  def mark_triggered(rule)
    redis = Redis.new(url: ENV.fetch("REDIS_URL", "redis://localhost:6379/0"))
    redis.setex("iot_rule_cooldown:#{rule.id}", rule.cooldown_minutes * 60, "1")
  end

  def create_work_order(rule, value)
    WorkOrder.create!(
      organization: rule.organization,
      asset: rule.asset,
      title: rule.work_order_title_for(value),
      description: "Auto-generated by IoT rule: #{rule.name} (#{rule.metric_name} #{rule.operator} #{rule.threshold})",
      priority: rule.priority,
      status: "open"
    )
  end
end
