class IotRule < ApplicationRecord
  # ─── Enums ─────────────────────────────────────────────────────────────────

  enum :status, { active: 0, paused: 1, archived: 2 }, default: :active
  enum :operator, { gt: 0, lt: 1, gte: 2, lte: 3, eq: 4, outside_range: 5 }, default: :gt
  enum :wo_priority, { critical: 0, high: 1, medium: 2, low: 3 }, default: :high, prefix: :wo

  # ─── Associations ──────────────────────────────────────────────────────────

  acts_as_tenant :organization
  belongs_to :asset
  belongs_to :organization
  belongs_to :created_by,  class_name: "User", optional: true
  belongs_to :assigned_to, class_name: "User", optional: true
  has_many   :iot_alerts,     dependent: :destroy
  has_many   :sensor_readings, foreign_key: :asset_id, primary_key: :asset_id,
                               class_name: "SensorReading"

  # ─── Validations ───────────────────────────────────────────────────────────

  validates :name,            presence: true
  validates :metric_name,     presence: true
  validates :threshold,       numericality: true
  validates :cooldown_minutes, numericality: { greater_than_or_equal_to: 0 }
  validates :threshold_max,   numericality: true, if: :outside_range?

  # ─── Scopes ────────────────────────────────────────────────────────────────

  scope :active_rules, -> { where(status: :active) }
  scope :for_asset,    ->(asset_id)  { where(asset_id: asset_id) }
  scope :for_metric,   ->(metric)    { where(metric_name: metric) }

  # ─── Breach Evaluation ─────────────────────────────────────────────────────

  def breach?(value)
    v = value.to_f
    case self.operator
    when "gt"           then v > threshold
    when "lt"           then v < threshold
    when "gte"          then v >= threshold
    when "lte"          then v <= threshold
    when "eq"           then v == threshold
    when "outside_range" then v < threshold || v > threshold_max.to_f
    else false
    end
  end

  def on_cooldown?
    return false unless last_wo_created_at && cooldown_minutes.to_i > 0
    last_wo_created_at > cooldown_minutes.minutes.ago
  end

  def build_wo_title(vars = {})
    interpolate(wo_title_template.presence || "{asset_name} - High {metric_name} Alert", vars)
  end

  def build_wo_description(vars = {})
    interpolate(wo_description_template.presence || default_wo_description, vars)
  end

  private

  def interpolate(template, vars)
    vars.reduce(template.dup) { |t, (k, v)| t.gsub("{#{k}}", v.to_s) }
  end

  def default_wo_description
    "Auto-generated by IoT rule \"#{name}\". " \
      "{metric_name} reading of {value} {unit} breached threshold of {threshold}."
  end
end
