class IoTRuleEvaluatorJob < ApplicationJob
  queue_as :default

  def perform(asset_id, readings)
    asset = Asset.find_by(id: asset_id)
    return unless asset

    rules = asset.iot_rules.active
    return if rules.none?

    readings.each do |metric_name, raw_value|
      value = raw_value.to_f
      rules.where(metric_name: metric_name).each do |rule|
        next unless rule.triggered_by?(value)
        next if on_cooldown?(rule)

        create_work_order(rule, asset, value) if rule.auto_create_wo
        rule.update_column(:last_triggered_at, Time.current)
      end
    end
  end

  private

  def on_cooldown?(rule)
    return false unless rule.last_triggered_at && rule.cooldown_minutes > 0
    rule.last_triggered_at > rule.cooldown_minutes.minutes.ago
  end

  def create_work_order(rule, asset, value)
    WorkOrder.create!(
      organization: asset.organization,
      asset: asset,
      title: rule.work_order_title_for(value),
      priority: rule.priority,
      status: "open",
      description: "Auto-generated by IoT rule \"#{rule.name}\" — #{rule.metric_name} #{rule.operator} #{rule.threshold}"
    )
  end
end
